name: Hub
author: DJBiokinetix
version: 5.0
main: com.djbiokinetix.hub.Main
description: |
    A Hub plugin for your Network.
api-version: 1.13
commands:
   /hub:
    description: Main command.
permissions:
   hub.event.join:
    default: op
   hub.event.join.firework:
    default: op